# Generated by Django 3.1.7 on 2021-05-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankingSystemApp', '0004_auto_20210517_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='balance'),
        ),
    ]
